import type { ViewStyle, TextStyle } from 'react-native';

import type { AppTheme } from '../theme';

type BrowserScreenStyleRecord = Record<string, ViewStyle | TextStyle>;

export function createBrowserScreenLayoutStyles(theme: AppTheme): BrowserScreenStyleRecord {
  return {
    container: {
      flex: 1,
      backgroundColor: theme.colors.bgMain,
    },
    safeArea: {
      flex: 1,
    },
    chrome: {
      paddingHorizontal: theme.spacing.md,
      paddingTop: theme.spacing.xs,
      paddingBottom: theme.spacing.sm,
      gap: theme.spacing.sm,
      backgroundColor: theme.colors.transparent,
    },
    viewportTray: {
      paddingBottom: theme.spacing.sm,
      flexShrink: 0,
    },
    viewportModeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
    },
    viewportModeScroller: {
      flex: 1,
    },
    viewportPresetRow: {
      gap: theme.spacing.xs,
      paddingRight: theme.spacing.md,
      minHeight: 34,
      alignItems: 'center',
    },
    viewportPresetChip: {
      minHeight: 30,
      paddingHorizontal: theme.spacing.md,
      borderRadius: theme.radius.full,
      borderWidth: 1,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgItem,
      alignItems: 'center',
      justifyContent: 'center',
    },
    viewportPresetChipActive: {
      borderColor: theme.colors.accent,
      backgroundColor: theme.colors.bgCanvasAccent,
    },
    viewportPresetChipPressed: {
      opacity: 0.86,
    },
    viewportPresetChipText: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      fontWeight: '600',
    },
    viewportPresetChipTextActive: {
      color: theme.colors.textPrimary,
    },
    viewportSettingsButton: {
      minHeight: 30,
      paddingHorizontal: theme.spacing.md,
      borderRadius: theme.radius.full,
      borderWidth: 1,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgItem,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: theme.spacing.xs,
    },
    viewportMenuBackdrop: {
      flex: 1,
      backgroundColor: theme.colors.overlayBackdrop,
      justifyContent: 'center',
      paddingHorizontal: theme.spacing.md,
    },
    viewportMenuKeyboardLayer: {
      width: '100%',
    },
    viewportMenuCard: {
      borderRadius: theme.radius.lg,
      borderWidth: 1,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgElevated,
      padding: theme.spacing.lg,
      gap: theme.spacing.md,
    },
    viewportMenuHeader: {
      gap: theme.spacing.xs,
    },
    viewportMenuTitle: {
      ...theme.typography.body,
      color: theme.colors.textPrimary,
      fontWeight: '700',
    },
    viewportMenuSubtitle: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      lineHeight: 18,
    },
    viewportMenuPresetGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.xs,
    },
    viewportMenuPresetChip: {
      minWidth: 96,
    },
    viewportInputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
      flexWrap: 'wrap',
    },
    viewportField: {
      minWidth: 84,
      paddingHorizontal: theme.spacing.sm,
      minHeight: 36,
      borderRadius: theme.radius.full,
      borderWidth: 1,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgInput,
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.xs,
    },
    viewportFieldLabel: {
      ...theme.typography.caption,
      color: theme.colors.textMuted,
      fontWeight: '700',
    },
    viewportFieldInput: {
      minWidth: 34,
      paddingVertical: 0,
      flex: 1,
      ...theme.typography.caption,
      color: theme.colors.textPrimary,
      fontWeight: '600',
    },
    viewportApplyButton: {
      minHeight: 36,
      paddingHorizontal: theme.spacing.md,
      borderRadius: theme.radius.full,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.accent,
    },
    viewportApplyButtonPressed: {
      backgroundColor: theme.colors.accentPressed,
    },
    viewportApplyButtonText: {
      ...theme.typography.caption,
      color: theme.colors.accentText,
      fontWeight: '700',
    },
    viewportCurrentLabel: {
      ...theme.typography.caption,
      color: theme.colors.textMuted,
      fontWeight: '600',
    },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
    },
    chromeButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgItem,
    },
    omnibox: {
      flex: 1,
      minHeight: 42,
      borderRadius: theme.radius.full,
      borderWidth: 1,
      borderColor: theme.colors.borderHighlight,
      backgroundColor: theme.colors.bgInput,
      paddingLeft: theme.spacing.md,
      paddingRight: theme.spacing.xs,
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
    },
    omniboxInput: {
      flex: 1,
      minWidth: 0,
      ...theme.typography.body,
      color: theme.colors.textPrimary,
      paddingVertical: theme.spacing.sm,
    },
    omniboxIconButton: {
      width: 24,
      height: 24,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    submitButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.accent,
    },
    submitButtonPressed: {
      backgroundColor: theme.colors.accentPressed,
    },
    submitButtonDisabled: {
      backgroundColor: theme.colors.bgItem,
    },
    navButtonDisabled: {
      opacity: 0.42,
    },
    iconButtonPressed: {
      backgroundColor: theme.colors.bgCanvasAccent,
    },
    statusBanner: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: theme.spacing.sm,
      marginHorizontal: theme.spacing.md,
      marginTop: theme.spacing.sm,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
    },
    statusBannerWarning: {
      backgroundColor: theme.colors.warningBg,
      borderColor: theme.colors.warningBorder,
    },
    statusBannerError: {
      backgroundColor: theme.colors.errorBg,
      borderColor: theme.colors.errorBorder,
    },
    statusBannerText: {
      ...theme.typography.caption,
      flex: 1,
      lineHeight: 18,
    },
    warningText: {
      color: theme.colors.warning,
    },
    errorText: {
      color: theme.colors.error,
    },
    contentArea: {
      flex: 1,
      minHeight: 0,
    },
    previewSurface: {
      flex: 1,
      minHeight: 0,
      marginHorizontal: 0,
      marginTop: 0,
      marginBottom: 0,
      borderRadius: 0,
      borderWidth: 0,
      overflow: 'hidden',
      backgroundColor: theme.colors.bgMain,
    },
    previewViewport: {
      flex: 1,
      minHeight: 0,
      overflow: 'hidden',
    },
    desktopScrollContent: {
      flexGrow: 1,
      minHeight: '100%',
    },
    desktopNativeScrollContent: {
      flexGrow: 1,
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
    },
    desktopNativeCanvas: {
      alignSelf: 'flex-start',
      backgroundColor: theme.colors.bgMain,
      overflow: 'hidden',
    },
    desktopNativeWebView: {
      backgroundColor: theme.colors.bgMain,
    },
    webView: {
      flex: 1,
      backgroundColor: theme.colors.bgMain,
    },
    loadingOverlay: {
      position: 'absolute',
      top: theme.spacing.sm,
      right: theme.spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      borderRadius: theme.radius.full,
      borderWidth: 1,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgElevated,
    },
    loadingText: {
      ...theme.typography.caption,
      color: theme.colors.textPrimary,
      fontWeight: '600',
    },
    bottomBarWrap: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.xs,
      backgroundColor: theme.colors.transparent,
    },
    bottomBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: 24,
      borderWidth: 1,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgItem,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
    },
    bottomNavButton: {
      width: 46,
      height: 38,
      borderRadius: 19,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bottomNavButtonActive: {
      backgroundColor: theme.colors.bgCanvasAccent,
      borderWidth: 1,
      borderColor: theme.colors.borderLight,
    },
    bottomNavButtonPrimary: {
      width: 46,
      height: 46,
      borderRadius: 23,
      backgroundColor: theme.colors.bgItem,
      borderWidth: 1,
      borderColor: theme.colors.borderLight,
    },
    bottomNavButtonPrimaryPressed: {
      backgroundColor: theme.colors.bgCanvasAccent,
    },
  };
}
