import { StyleSheet } from 'react-native';

import type { AppTheme } from '../theme';

export function createGitScreenDiffReviewStyles(theme: AppTheme) {
  return StyleSheet.create({
    diffSummaryRow: {
      flexDirection: 'row',
      gap: theme.spacing.sm,
    },
    diffSummaryPill: {
      flex: 1,
      backgroundColor: theme.colors.bgItem,
      borderRadius: theme.radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      gap: 2,
    },
    diffSummaryLabel: {
      ...theme.typography.caption,
      color: theme.colors.textMuted,
    },
    diffSummaryValue: {
      ...theme.typography.body,
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
    diffCard: {
      backgroundColor: theme.colors.bgItem,
      borderRadius: theme.radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      overflow: 'hidden',
    },
    diffTabsScroll: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.borderLight,
    },
    diffTabsContent: {
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.sm,
      gap: theme.spacing.sm,
    },
    diffTab: {
      minWidth: 140,
      maxWidth: 220,
      backgroundColor: theme.colors.bgInput,
      borderRadius: theme.radius.sm,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.sm,
      gap: theme.spacing.xs,
    },
    diffTabActive: {
      borderColor: theme.colors.borderHighlight,
      backgroundColor: theme.colors.bgItem,
    },
    diffTabPressed: {
      opacity: 0.85,
    },
    diffTabTitle: {
      ...theme.typography.body,
      color: theme.colors.textPrimary,
      flexShrink: 1,
      fontSize: 13,
      lineHeight: 18,
    },
    diffTabStats: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.xs,
    },
    diffTabCommentCount: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      fontSize: 10,
      lineHeight: 13,
    },
    diffFileHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.md,
      justifyContent: 'space-between',
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.borderLight,
    },
    diffFilePath: {
      ...theme.typography.body,
      color: theme.colors.textSecondary,
      flex: 1,
      flexShrink: 1,
      fontSize: 13,
      lineHeight: 18,
    },
    diffFileStatus: {
      ...theme.typography.caption,
      textTransform: 'uppercase',
      letterSpacing: 0,
      color: theme.colors.textMuted,
    },
    diffLoadingContainer: {
      minHeight: 120,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.lg,
      gap: theme.spacing.sm,
    },
    diffLoadingText: {
      ...theme.typography.caption,
      color: theme.colors.textMuted,
    },
    diffVerticalScroll: {
      minHeight: 120,
    },
    diffVerticalContent: {
      paddingVertical: theme.spacing.sm,
    },
    diffLines: {
      minWidth: '100%',
    },
    hunkBlock: {
      marginBottom: theme.spacing.sm,
    },
    hunkHeader: {
      ...theme.typography.mono,
      color: theme.colors.accent,
      backgroundColor: theme.colors.toolBlockBg,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.xs,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.colors.borderLight,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.borderLight,
    },
    diffLineRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      minWidth: '100%',
    },
    diffCommentButton: {
      width: 28,
      minHeight: 23,
      alignItems: 'center',
      justifyContent: 'center',
      borderRightWidth: StyleSheet.hairlineWidth,
      borderRightColor: theme.colors.borderLight,
    },
    diffCommentButtonActive: {
      backgroundColor: theme.colors.bgInput,
    },
    diffCommentButtonPressed: {
      backgroundColor: theme.colors.bgElevated,
    },
    diffLineRowAdd: {
      backgroundColor: theme.colors.successBg,
    },
    diffLineRowRemove: {
      backgroundColor: theme.colors.errorBg,
    },
    diffLineRowMeta: {
      backgroundColor: theme.colors.bgCanvasAccent,
    },
    diffLineNumber: {
      ...theme.typography.mono,
      width: 44,
      textAlign: 'right',
      color: theme.colors.textMuted,
      paddingHorizontal: theme.spacing.xs,
      paddingVertical: 3,
      fontSize: 11,
      lineHeight: 17,
    },
    diffLinePrefix: {
      ...theme.typography.mono,
      width: 16,
      color: theme.colors.textMuted,
      paddingVertical: 3,
      fontSize: 11,
      lineHeight: 17,
    },
    diffLinePrefixAdd: {
      color: theme.colors.statusComplete,
    },
    diffLinePrefixRemove: {
      color: theme.colors.statusError,
    },
    diffLinePrefixMeta: {
      color: theme.colors.textMuted,
    },
    diffLineText: {
      ...theme.typography.mono,
      color: theme.colors.textPrimary,
      paddingRight: theme.spacing.md,
      paddingVertical: 3,
      fontSize: 12,
      lineHeight: 17,
    },
    inlineReviewComment: {
      marginLeft: 28,
      marginRight: theme.spacing.md,
      marginVertical: theme.spacing.xs,
      padding: theme.spacing.sm,
      minWidth: 320,
      borderRadius: theme.radius.sm,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderHighlight,
      backgroundColor: theme.colors.bgElevated,
      gap: 4,
    },
    inlineReviewCommentHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: theme.spacing.md,
    },
    inlineReviewCommentAnchor: {
      ...theme.typography.caption,
      color: theme.colors.textMuted,
      fontWeight: '700',
      fontSize: 10,
      textTransform: 'uppercase',
    },
    inlineReviewCommentActions: {
      flexDirection: 'row',
      gap: theme.spacing.sm,
    },
    inlineReviewCommentAction: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      fontWeight: '700',
    },
    inlineReviewCommentDelete: {
      ...theme.typography.caption,
      color: theme.colors.error,
      fontWeight: '700',
    },
    inlineReviewCommentText: {
      ...theme.typography.body,
      color: theme.colors.textPrimary,
      fontSize: 13,
      lineHeight: 18,
    },
    reviewTray: {
      borderRadius: theme.radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderHighlight,
      backgroundColor: theme.colors.bgItem,
      padding: theme.spacing.md,
      gap: theme.spacing.sm,
    },
    reviewTrayHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: theme.spacing.md,
    },
    reviewTrayTitle: {
      ...theme.typography.headline,
      color: theme.colors.textPrimary,
      fontSize: 16,
    },
    reviewTraySubtitle: {
      ...theme.typography.caption,
      color: theme.colors.textMuted,
      marginTop: 2,
    },
    reviewTrayClear: {
      ...theme.typography.caption,
      color: theme.colors.error,
      fontWeight: '700',
    },
    reviewTrayComment: {
      borderRadius: theme.radius.sm,
      backgroundColor: theme.colors.bgInput,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: 7,
      gap: 2,
    },
    reviewTrayCommentPressed: {
      backgroundColor: theme.colors.bgElevated,
    },
    reviewTrayCommentAnchor: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      fontWeight: '700',
    },
    reviewTrayCommentText: {
      ...theme.typography.caption,
      color: theme.colors.textPrimary,
    },
    submitReviewButton: {
      minHeight: 44,
      borderRadius: theme.radius.sm,
      backgroundColor: theme.colors.accent,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: theme.spacing.sm,
      paddingHorizontal: theme.spacing.md,
    },
    submitReviewButtonText: {
      ...theme.typography.body,
      color: theme.colors.accentText,
      fontWeight: '700',
    },
    reviewModalBackdrop: {
      flex: 1,
      justifyContent: 'center',
      padding: theme.spacing.lg,
      backgroundColor: theme.colors.overlayBackdrop,
    },
    reviewModalCard: {
      borderRadius: theme.radius.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderHighlight,
      backgroundColor: theme.colors.bgElevated,
      padding: theme.spacing.lg,
      gap: theme.spacing.md,
    },
    reviewModalHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: theme.spacing.md,
    },
    reviewModalTitleBlock: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    reviewModalEyebrow: {
      ...theme.typography.caption,
      color: theme.colors.textMuted,
      textTransform: 'uppercase',
      fontWeight: '700',
      fontSize: 10,
    },
    reviewModalTitle: {
      ...theme.typography.body,
      color: theme.colors.textPrimary,
      fontWeight: '700',
    },
    reviewCommentInput: {
      ...theme.typography.body,
      color: theme.colors.textPrimary,
      minHeight: 130,
      maxHeight: 260,
      borderRadius: theme.radius.sm,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderHighlight,
      backgroundColor: theme.colors.bgInput,
      padding: theme.spacing.md,
    },
    reviewModalActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: theme.spacing.sm,
    },
    reviewModalCancel: {
      minHeight: 42,
      justifyContent: 'center',
      paddingHorizontal: theme.spacing.md,
    },
    reviewModalCancelText: {
      ...theme.typography.body,
      color: theme.colors.textSecondary,
      fontWeight: '600',
    },
    reviewModalSave: {
      minHeight: 42,
      justifyContent: 'center',
      borderRadius: theme.radius.sm,
      backgroundColor: theme.colors.accent,
      paddingHorizontal: theme.spacing.lg,
    },
    reviewModalSaveText: {
      ...theme.typography.body,
      color: theme.colors.accentText,
      fontWeight: '700',
    },
  });
}