import { StyleSheet } from 'react-native';

import type { AppTheme } from '../theme';

export const createMainScreenWorkflowStyles = (theme: AppTheme) => ({
  planCard: { borderWidth: StyleSheet.hairlineWidth, borderColor: theme.colors.borderLight, borderRadius: 12, backgroundColor: theme.colors.bgItem, padding: theme.spacing.md, marginBottom: theme.spacing.sm },
  planOverlayCard: { marginBottom: 0, boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.16)' },
  queuedMessageCard: { marginBottom: 0, paddingHorizontal: theme.spacing.md, paddingVertical: theme.spacing.sm, borderRadius: 10 },
  queuedMessageHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: theme.spacing.sm, marginBottom: theme.spacing.xs / 2 },
  queuedMessageHeaderText: { flex: 1, gap: 2 },
  queuedMessageActions: { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.xs },
  queuedMessageSummary: { ...theme.typography.caption, color: theme.colors.textSecondary },
  queuedMessageBody: { ...theme.typography.caption, color: theme.colors.textPrimary, lineHeight: 18 },
  queuedMessageHint: { ...theme.typography.caption, color: theme.colors.textMuted, marginTop: theme.spacing.xs },
  workflowSection: { marginTop: theme.spacing.md, gap: theme.spacing.xs },
  workflowSectionEyebrow: { ...theme.typography.caption, color: theme.colors.textMuted, textTransform: 'uppercase', letterSpacing: 0 },
  workflowScrollViewport: { marginTop: theme.spacing.xs },
  workflowScrollContent: { paddingBottom: theme.spacing.xs },
  workflowSummaryText: { ...theme.typography.caption, color: theme.colors.textPrimary, lineHeight: 18 },
  workflowMetaText: { ...theme.typography.caption, color: theme.colors.textSecondary },
  queuedMessageActionButton: { flexShrink: 0, borderRadius: 999, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.colors.borderHighlight, backgroundColor: theme.colors.inlineCodeBg, paddingHorizontal: theme.spacing.sm, paddingVertical: 5 },
  queuedMessageActionButtonDestructive: { borderColor: theme.colors.error, backgroundColor: theme.colors.errorBg },
  queuedMessageActionButtonDisabled: { borderColor: theme.colors.border, backgroundColor: theme.colors.bgMain },
  queuedMessageActionButtonPressed: { opacity: 0.88 },
  queuedMessageActionLabel: { ...theme.typography.caption, color: theme.colors.textPrimary, fontWeight: '700' },
  queuedMessageActionLabelDestructive: { color: theme.colors.error },
  queuedMessageActionLabelDisabled: { color: theme.colors.textMuted },
  planCardHeader: { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.xs, marginBottom: theme.spacing.xs },
  planCardHeaderPressable: { marginBottom: 0 },
  planCardHeaderText: { flex: 1, gap: 2 },
  planCardTitle: { ...theme.typography.caption, color: theme.colors.textPrimary, fontWeight: '700' },
  planCardSummary: { ...theme.typography.caption, color: theme.colors.textSecondary },
  planExplanationText: { ...theme.typography.caption, color: theme.colors.textSecondary, fontStyle: 'italic', marginTop: theme.spacing.sm, marginBottom: theme.spacing.sm },
  planStepsList: { gap: theme.spacing.xs },
  planStepRow: { flexDirection: 'row', alignItems: 'flex-start', gap: theme.spacing.sm },
  planStepMarkdownWrap: { flex: 1, minWidth: 0 },
  planStepStatus: { ...theme.typography.caption, color: theme.colors.textMuted, marginTop: 1 },
  planStepStatusCompleted: { color: theme.colors.textMuted },
  planStepStatusInProgress: { color: theme.colors.accent, fontWeight: '700' },
  planStepStatusPending: { color: theme.colors.textMuted },
  planStepText: { ...theme.typography.caption, color: theme.colors.textPrimary, flex: 1 },
  planStepTextCompleted: { color: theme.colors.textMuted, textDecorationLine: 'line-through' },
  planStepTextInProgress: { color: theme.colors.textPrimary, fontWeight: '700' },
  planStepTextPending: { color: theme.colors.textPrimary },
  planDeltaText: { ...theme.typography.caption, color: theme.colors.textMuted, marginTop: theme.spacing.xs },
  renameModalBackdrop: { flex: 1, backgroundColor: theme.colors.overlayBackdrop, paddingHorizontal: theme.spacing.lg, justifyContent: 'center' },
  renameModalKeyboardAvoider: { flex: 1 },
  renameModalKeyboardContent: { flex: 1, justifyContent: 'center' },
  renameModalKeyboardContentBottom: { justifyContent: 'flex-end' },
  workspaceModalLoading: { ...theme.typography.caption, color: theme.colors.textMuted },
  inlineMentionStatus: { marginHorizontal: theme.spacing.lg, marginBottom: theme.spacing.xs },
  slashSuggestions: { marginHorizontal: theme.spacing.lg, marginBottom: theme.spacing.xs, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.colors.borderLight, backgroundColor: theme.colors.bgItem, overflow: 'hidden' },
  slashSuggestionsContent: { paddingVertical: 0 },
  slashSuggestionItem: { paddingHorizontal: theme.spacing.md, paddingVertical: theme.spacing.sm, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.colors.borderLight },
  slashSuggestionItemLast: { borderBottomWidth: 0 },
  slashSuggestionItemPressed: { backgroundColor: theme.colors.bgInput },
  slashSuggestionTitle: { ...theme.typography.body, color: theme.colors.textPrimary, fontWeight: '600' },
  slashSuggestionSummary: { ...theme.typography.caption, color: theme.colors.textMuted, marginTop: 2 },
  renameModalCard: { backgroundColor: theme.colors.bgItem, borderRadius: 14, borderWidth: 1, borderColor: theme.colors.border, padding: theme.spacing.lg, gap: theme.spacing.md, maxHeight: '82%' },
  renameModalTitle: { ...theme.typography.headline, color: theme.colors.textPrimary },
  attachmentModalHint: { ...theme.typography.caption, color: theme.colors.textSecondary },
  attachmentSuggestionsList: { maxHeight: 170, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.colors.borderLight, borderRadius: 10, backgroundColor: theme.colors.bgMain },
  attachmentSuggestionsListContent: { paddingVertical: 0 },
  attachmentSuggestionItem: { paddingHorizontal: theme.spacing.md, paddingVertical: theme.spacing.sm, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.colors.borderLight },
  attachmentSuggestionItemLast: { borderBottomWidth: 0 },
  attachmentSuggestionItemPressed: { backgroundColor: theme.colors.bgInput },
  attachmentSuggestionText: { ...theme.typography.caption, color: theme.colors.textPrimary },
  renameModalInput: { color: theme.colors.textPrimary, backgroundColor: theme.colors.bgInput, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 10, paddingHorizontal: theme.spacing.md, paddingVertical: theme.spacing.sm, fontSize: 15 },
  gitCheckoutHint: { ...theme.typography.caption, color: theme.colors.textSecondary, lineHeight: 18 },
  gitCheckoutPathButton: { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 10, backgroundColor: theme.colors.bgMain, paddingHorizontal: theme.spacing.md, paddingVertical: theme.spacing.sm },
  gitCheckoutPathButtonPressed: { opacity: 0.85 },
  gitCheckoutPathCopy: { flex: 1, gap: 2 },
  gitCheckoutPathLabel: { ...theme.typography.caption, color: theme.colors.textMuted },
  gitCheckoutPathValue: { ...theme.typography.caption, color: theme.colors.textPrimary, fontWeight: '600' },
  gitCheckoutSummary: { ...theme.typography.caption, color: theme.colors.textMuted },
  gitCheckoutErrorText: { ...theme.typography.caption, color: theme.colors.error },
} as const);