import { StyleSheet } from 'react-native';

import type { AppTheme } from '../theme';

export const createMainScreenModalStyles = (theme: AppTheme) => ({
  attachmentListColumn: { gap: theme.spacing.xs, maxHeight: 180 },
  attachmentListRow: { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.colors.borderLight, borderRadius: 8, backgroundColor: theme.colors.bgMain, paddingHorizontal: theme.spacing.sm, paddingVertical: theme.spacing.xs },
  attachmentListPath: { ...theme.typography.caption, color: theme.colors.textPrimary, flex: 1 },
  attachmentRemoveButton: { width: 22, height: 22, borderRadius: 11, alignItems: 'center', justifyContent: 'center', borderWidth: StyleSheet.hairlineWidth, borderColor: theme.colors.border, backgroundColor: theme.colors.bgItem },
  attachmentRemoveButtonPressed: { opacity: 0.8 },
  renameModalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: theme.spacing.sm },
  renameModalButton: { borderRadius: 10, paddingHorizontal: theme.spacing.lg, paddingVertical: theme.spacing.sm, borderWidth: 1 },
  renameModalButtonSecondary: { borderColor: theme.colors.border, backgroundColor: theme.colors.bgMain },
  renameModalButtonSecondaryText: { ...theme.typography.body, color: theme.colors.textPrimary },
  renameModalButtonPrimary: { borderColor: theme.colors.accent, backgroundColor: theme.colors.accent },
  renameModalButtonPrimaryPressed: { backgroundColor: theme.colors.accentPressed, borderColor: theme.colors.accentPressed },
  renameModalButtonDisabled: { opacity: 0.45 },
  renameModalButtonPressed: { opacity: 0.8 },
  renameModalButtonPrimaryText: { ...theme.typography.body, color: theme.colors.accentText, fontWeight: '600' },
  userInputModalBackdrop: { flex: 1, backgroundColor: theme.colors.overlayBackdrop, justifyContent: 'center', paddingHorizontal: theme.spacing.lg },
  userInputModalCard: { backgroundColor: theme.colors.bgItem, borderRadius: 14, borderWidth: 1, borderColor: theme.colors.borderHighlight, padding: theme.spacing.lg, gap: theme.spacing.md, maxHeight: '80%' },
  planPromptModalCard: { backgroundColor: theme.colors.bgItem, borderRadius: 14, borderWidth: 1, borderColor: theme.colors.borderHighlight, padding: theme.spacing.lg, gap: theme.spacing.md, maxHeight: '80%' },
  userInputModalTitle: { ...theme.typography.headline, color: theme.colors.textPrimary },
  planPromptOptionsColumn: { gap: theme.spacing.sm },
  planPromptOptionButton: { borderWidth: StyleSheet.hairlineWidth, borderColor: theme.colors.border, backgroundColor: theme.colors.bgMain, borderRadius: 10, paddingHorizontal: theme.spacing.md, paddingVertical: theme.spacing.md, gap: theme.spacing.xs },
  planPromptOptionButtonPressed: { opacity: 0.88 },
  planPromptOptionButtonDisabled: { opacity: 0.45 },
  planPromptOptionTitle: { ...theme.typography.body, color: theme.colors.textPrimary, fontWeight: '600' },
  planPromptOptionTitleDisabled: { color: theme.colors.textMuted },
  planPromptOptionDescription: { ...theme.typography.caption, color: theme.colors.textSecondary },
  planPromptOptionDescriptionDisabled: { color: theme.colors.textMuted },
  userInputQuestionsList: { maxHeight: 380 },
  userInputQuestionsListContent: { gap: theme.spacing.md },
  userInputQuestionCard: { borderWidth: StyleSheet.hairlineWidth, borderColor: theme.colors.borderLight, borderRadius: 10, backgroundColor: theme.colors.bgMain, padding: theme.spacing.sm, gap: theme.spacing.xs },
  userInputQuestionHeader: { ...theme.typography.caption, color: theme.colors.textPrimary, fontWeight: '700' },
  userInputQuestionText: { ...theme.typography.caption, color: theme.colors.textSecondary },
  userInputOptionsColumn: { gap: theme.spacing.xs, marginTop: theme.spacing.xs },
  userInputOptionButton: { borderWidth: StyleSheet.hairlineWidth, borderColor: theme.colors.border, backgroundColor: theme.colors.bgItem, borderRadius: 10, paddingHorizontal: theme.spacing.sm, paddingVertical: theme.spacing.sm, gap: 2 },
  userInputOptionButtonSelected: { borderColor: theme.colors.borderHighlight, backgroundColor: theme.colors.bgInput },
  userInputOptionButtonPressed: { opacity: 0.85 },
  userInputOptionHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm },
  userInputOptionIndex: { ...theme.typography.caption, color: theme.colors.textMuted, fontWeight: '700', minWidth: 18 },
  userInputOptionLabel: { ...theme.typography.caption, color: theme.colors.textPrimary, flex: 1, fontWeight: '600' },
  userInputOptionDescription: { ...theme.typography.caption, color: theme.colors.textMuted },
  userInputAnswerInput: { color: theme.colors.textPrimary, backgroundColor: theme.colors.bgInput, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 8, paddingHorizontal: theme.spacing.sm, paddingVertical: theme.spacing.sm, minHeight: 42, textAlignVertical: 'top' },
  userInputAnswerInputSecret: { textAlignVertical: 'center' },
  userInputErrorText: { ...theme.typography.caption, color: theme.colors.error },
  userInputModalActions: { flexDirection: 'row', flexWrap: 'wrap', gap: theme.spacing.sm },
  userInputSecondaryButton: { borderWidth: 1, borderColor: theme.colors.border, borderRadius: 10, paddingHorizontal: theme.spacing.md, paddingVertical: theme.spacing.sm, alignItems: 'center' },
  userInputSecondaryButtonText: { ...theme.typography.body, color: theme.colors.textSecondary, fontWeight: '600' },
  userInputSubmitButton: { flexGrow: 1, borderWidth: 1, borderColor: theme.colors.borderHighlight, backgroundColor: theme.colors.bgInput, borderRadius: 10, paddingVertical: theme.spacing.sm, alignItems: 'center' },
  userInputSubmitButtonPressed: { opacity: 0.88 },
  userInputSubmitButtonDisabled: { opacity: 0.45 },
  userInputSubmitButtonText: { ...theme.typography.body, color: theme.colors.textPrimary, fontWeight: '700' },
} as const);