import { StyleSheet } from 'react-native';

import type { AppTheme } from '../theme';

export const createMainScreenAgentStyles = (theme: AppTheme) => {
  const agentPanelShadow = theme.isDark
    ? '0 12px 30px rgba(0, 0, 0, 0.22)'
    : '0 12px 24px rgba(15, 23, 42, 0.12)';

  return {
    agentPanelWrap: { backgroundColor: theme.colors.bgMain, paddingHorizontal: theme.spacing.lg, paddingBottom: theme.spacing.sm },
    agentPanelCard: {
      borderRadius: 18,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgElevated,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.md,
      gap: theme.spacing.sm,
      boxShadow: agentPanelShadow,
    },
    agentPanelHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: theme.spacing.sm },
    agentPanelHeaderPressable: { borderRadius: theme.radius.md },
    agentPanelHeaderPressed: { opacity: 0.84 },
    agentPanelHeaderCopy: { flex: 1, gap: 2 },
    agentPanelEyebrow: { ...theme.typography.caption, color: theme.colors.textMuted, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0 },
    agentPanelSummary: { ...theme.typography.caption, color: theme.colors.textMuted },
    agentPanelList: { gap: theme.spacing.sm },
    agentPanelScroll: { flexGrow: 0 },
    agentPanelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
      borderRadius: theme.radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgItem,
      paddingHorizontal: theme.spacing.sm + 2,
      paddingVertical: theme.spacing.sm + 2,
    },
    agentPanelRowSelected: { borderColor: theme.colors.borderHighlight, backgroundColor: theme.colors.bgInput },
    agentPanelRowPressed: { opacity: 0.84 },
    agentPanelAccent: { width: 4, alignSelf: 'stretch', borderRadius: 999, flexShrink: 0 },
    agentPanelCopy: { flex: 1, gap: 2, minWidth: 0 },
    agentPanelTitleRow: { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.xs },
    agentPanelTitle: { ...theme.typography.body, fontSize: 13, lineHeight: 18, fontWeight: '700', flex: 1 },
    agentPanelSelectedLabel: { ...theme.typography.caption, color: theme.colors.textMuted, fontWeight: '600' },
    agentPanelDescription: { ...theme.typography.caption, color: theme.colors.textMuted, fontSize: 11, lineHeight: 15 },
    agentPanelStatusBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.xs,
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: 5,
      maxWidth: '42%',
      flexShrink: 0,
    },
    agentPanelStatusText: { ...theme.typography.caption, fontSize: 11, lineHeight: 14, fontWeight: '700' },
    modelChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgElevated,
      minHeight: 28,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: 5,
      flexShrink: 0,
    },
    modeChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgElevated,
      minHeight: 28,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: 5,
      flexShrink: 0,
    },
    fastChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgElevated,
      minHeight: 28,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: 5,
      flexShrink: 0,
    },
    fastChipEnabled: { borderColor: theme.colors.successBorder, backgroundColor: theme.colors.successBg },
    modelChipPressed: { opacity: 0.86 },
    sessionMetaChipDisabled: { opacity: 0.5 },
    modelChipText: { ...theme.typography.caption, color: theme.colors.textSecondary, fontSize: 11, lineHeight: 14, fontWeight: '600' },
    inlineOptionsGroup: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgMain,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      gap: theme.spacing.sm,
      maxHeight: 320,
    },
    inlineOptionsHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: theme.spacing.sm },
    inlineOptionsTitle: { ...theme.typography.body, color: theme.colors.textPrimary, fontWeight: '700' },
    inlineOptionsClose: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center', borderRadius: 6 },
    inlineOptionsScroll: { flexGrow: 0 },
    inlineOptionsContent: { gap: theme.spacing.xs },
    inlineOptionsLoading: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm },
    inlineOption: {
      minHeight: 46,
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      borderRadius: 8,
      backgroundColor: theme.colors.bgItem,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
    },
    inlineOptionSelected: { borderColor: theme.colors.borderHighlight, backgroundColor: theme.colors.bgInput },
    inlineOptionDisabled: { opacity: 0.45 },
    inlineOptionPressed: { opacity: 0.84 },
    inlineOptionCopy: { flex: 1, minWidth: 0, gap: 2 },
    inlineOptionTitle: { ...theme.typography.body, color: theme.colors.textPrimary, fontSize: 13, lineHeight: 18, fontWeight: '600' },
    inlineOptionsDescription: { ...theme.typography.caption, color: theme.colors.textMuted, fontSize: 11, lineHeight: 15 },
    fastChipTextEnabled: { color: theme.colors.textPrimary },
  } as const;
};