import { StyleSheet } from 'react-native';

import type { AppTheme } from '../theme';
import type { OnboardingStyleTokens } from './onboardingScreenStyleTokens';

export const createOnboardingFormStyles = (theme: AppTheme, tokens: OnboardingStyleTokens) =>
  StyleSheet.create({
    formCard: {
      borderRadius: 20,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderHighlight,
      backgroundColor: tokens.glassDockBackground,
      padding: theme.spacing.lg,
      gap: theme.spacing.md,
      overflow: 'hidden',
    },
    connectPrimaryActions: {
      gap: theme.spacing.sm,
    },
    connectActionPrimary: {
      minHeight: 48,
    },
    formSectionHeader: {
      gap: theme.spacing.xs,
    },
    formSectionEyebrow: {
      ...theme.typography.caption,
      color: theme.colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0,
    },
    formSectionTitle: {
      ...theme.typography.headline,
      fontSize: 15,
      lineHeight: 21,
    },
    commandPanel: {
      gap: theme.spacing.sm,
      paddingTop: theme.spacing.xs,
    },
    commandCard: {
      gap: theme.spacing.xs,
      borderRadius: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      backgroundColor: tokens.glassSubtleBackground,
      padding: theme.spacing.md,
    },
    commandCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: theme.spacing.sm,
    },
    commandCardHeaderLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flex: 1,
      minWidth: 0,
    },
    commandCardActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.xs,
      flexShrink: 0,
    },
    commandCardLabel: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      fontWeight: '600',
      letterSpacing: 0,
    },
    commandCopyButton: {
      minHeight: 30,
      paddingHorizontal: theme.spacing.sm,
      borderRadius: theme.radius.full,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.bgInput,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      flexShrink: 0,
    },
    commandCopyButtonCopied: {
      backgroundColor: theme.colors.accent,
      borderColor: theme.colors.accent,
    },
    commandCopyButtonPressed: {
      opacity: 0.84,
    },
    commandIconButton: {
      width: 30,
      height: 30,
      borderRadius: theme.radius.full,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.bgInput,
      alignItems: 'center',
      justifyContent: 'center',
    },
    commandCopyButtonText: {
      ...theme.typography.caption,
      color: theme.colors.textPrimary,
      fontWeight: '600',
    },
    commandCopyButtonTextCopied: {
      color: theme.colors.accentText,
    },
    commandCodeWrap: {
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.bgInput,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.sm,
    },
    commandCodeText: {
      ...theme.typography.mono,
      color: theme.colors.textPrimary,
      fontSize: 12,
      lineHeight: 18,
    },
    fieldGroup: {
      gap: theme.spacing.sm,
    },
    label: {
      ...theme.typography.caption,
      textTransform: 'uppercase',
      letterSpacing: 0,
      color: theme.colors.textMuted,
    },
    inputRow: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 16,
      backgroundColor: tokens.glassSubtleBackground,
      minHeight: 54,
      paddingHorizontal: theme.spacing.md,
      gap: theme.spacing.sm,
    },
    inputIconWrap: {
      width: 24,
      alignItems: 'center',
      justifyContent: 'center',
    },
    inputText: {
      flex: 1,
      minWidth: 0,
      ...theme.typography.body,
      color: theme.colors.textPrimary,
      paddingVertical: theme.spacing.md,
    },
    tokenInputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.xs,
      minWidth: 0,
    },
    tokenRevealBtn: {
      minWidth: 74,
      minHeight: 54,
      flexShrink: 0,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.bgInput,
      paddingHorizontal: theme.spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
    },
    tokenRevealBtnPressed: {
      opacity: 0.8,
    },
    tokenRevealBtnText: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      fontWeight: '600',
    },
    scanButton: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.bgInput,
      minHeight: 50,
      paddingHorizontal: theme.spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: theme.spacing.xs,
    },
    scanButtonPressed: {
      opacity: 0.82,
    },
    scanButtonText: {
      ...theme.typography.headline,
      color: theme.colors.textPrimary,
      fontWeight: '700',
    },
    statusBanner: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: theme.spacing.sm,
      borderRadius: 16,
      borderWidth: StyleSheet.hairlineWidth,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
    },
    statusBannerWarning: {
      backgroundColor: theme.isDark ? 'rgba(247, 210, 126, 0.08)' : 'rgba(197, 106, 18, 0.12)',
      borderColor: 'rgba(247, 210, 126, 0.22)',
    },
    statusBannerSuccess: {
      backgroundColor: theme.isDark ? 'rgba(198, 205, 217, 0.10)' : 'rgba(14, 159, 110, 0.10)',
      borderColor: theme.isDark ? 'rgba(198, 205, 217, 0.22)' : 'rgba(14, 159, 110, 0.24)',
    },
    statusBannerError: {
      backgroundColor: theme.colors.errorBg,
      borderColor: 'rgba(239, 68, 68, 0.28)',
    },
    statusBannerText: {
      flex: 1,
      ...theme.typography.caption,
      lineHeight: 18,
    },
    warningText: {
      ...theme.typography.caption,
      color: theme.colors.warning,
    },
    errorText: {
      ...theme.typography.caption,
      color: theme.colors.error,
    },
    successText: {
      ...theme.typography.caption,
      color: theme.colors.statusComplete,
    },
    actionRow: {
      flexDirection: 'row',
      gap: theme.spacing.sm,
    },
    secondaryButton: {
      flex: 1,
      flexDirection: 'row',
      gap: theme.spacing.xs,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.bgInput,
      borderRadius: 16,
      minHeight: 54,
    },
    secondaryButtonPressed: {
      opacity: 0.8,
    },
    secondaryButtonDisabled: {
      opacity: 0.65,
    },
    secondaryButtonText: {
      ...theme.typography.caption,
      color: theme.colors.textPrimary,
      fontWeight: '600',
    },
    primaryButton: {
      flex: 1,
      flexDirection: 'row',
      gap: theme.spacing.xs,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.accent,
      borderRadius: 16,
      minHeight: 54,
    },
    connectFooterButton: {
      flex: 0,
      minHeight: 78,
      borderRadius: 24,
      justifyContent: 'flex-start',
      paddingHorizontal: theme.spacing.md,
      gap: theme.spacing.md,
    },
    primaryButtonPressed: {
      backgroundColor: theme.colors.accentPressed,
    },
    primaryButtonDisabled: {
      opacity: 0.72,
    },
    primaryButtonText: {
      ...theme.typography.headline,
      color: theme.colors.accentText,
      fontWeight: '700',
    },
    primaryButtonIconWrap: {
      width: 46,
      height: 46,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.isDark ? 'rgba(0,0,0,0.08)' : 'rgba(255,255,255,0.38)',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.isDark ? 'rgba(0,0,0,0.10)' : 'rgba(255,255,255,0.48)',
    },
    primaryButtonContent: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: theme.spacing.md,
    },
    primaryButtonCopy: {
      flex: 1,
      minWidth: 0,
      alignItems: 'flex-start',
      gap: 2,
    },
    primaryButtonSubtext: {
      ...theme.typography.caption,
      color: theme.colors.accentText,
      opacity: 0.72,
      fontWeight: '600',
    },
  });
