import { StyleSheet } from 'react-native';

import type { AppTheme } from '../theme';

export const createMarkdownStyles = (theme: AppTheme) => StyleSheet.create({
  body: {
    ...theme.typography.body,
    color: theme.colors.textPrimary,
  },
  heading1: {
    ...theme.typography.headline,
    color: theme.colors.textPrimary,
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 0,
    marginTop: theme.spacing.md,
    marginBottom: theme.spacing.xs,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  heading2: {
    ...theme.typography.headline,
    color: theme.colors.textPrimary,
    fontSize: 17,
    lineHeight: 23,
    letterSpacing: 0,
    marginTop: theme.spacing.md,
    marginBottom: theme.spacing.xs,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  heading3: {
    ...theme.typography.headline,
    color: theme.colors.textPrimary,
    fontSize: 15,
    lineHeight: 21,
    letterSpacing: 0,
    marginTop: theme.spacing.sm,
    marginBottom: theme.spacing.xs,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  heading4: {
    ...theme.typography.headline,
    color: theme.colors.textPrimary,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
    marginTop: theme.spacing.sm,
    marginBottom: theme.spacing.xs,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  heading5: {
    ...theme.typography.headline,
    color: theme.colors.textPrimary,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
    marginTop: theme.spacing.sm,
    marginBottom: theme.spacing.xs,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  heading6: {
    ...theme.typography.headline,
    color: theme.colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: 0,
    marginTop: theme.spacing.sm,
    marginBottom: theme.spacing.xs,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  code_inline: {
    fontFamily: theme.fonts.monoRegular,
    fontSize: 12,
    backgroundColor: theme.colors.inlineCodeBg,
    color: theme.colors.inlineCodeText,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.inlineCodeBorder,
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  code_block: {
    fontFamily: theme.fonts.monoRegular,
    fontSize: 12,
    backgroundColor: theme.colors.bgInput,
    color: theme.colors.textPrimary,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderHighlight,
    borderRadius: theme.radius.sm,
    padding: theme.spacing.md,
    marginVertical: theme.spacing.sm,
  },
  fence: {
    fontFamily: theme.fonts.monoRegular,
    fontSize: 12,
    backgroundColor: theme.colors.bgInput,
    color: theme.colors.textPrimary,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderHighlight,
    borderRadius: theme.radius.sm,
    padding: theme.spacing.md,
    marginVertical: theme.spacing.sm,
  },
  link: {
    color: theme.colors.accent,
    textDecorationLine: 'underline',
  },
  paragraph: {
    marginTop: theme.spacing.xs,
    marginBottom: theme.spacing.xs,
  },
  bullet_list: {
    marginVertical: theme.spacing.xs,
  },
  ordered_list: {
    marginVertical: theme.spacing.xs,
  },
  list_item: {
    marginVertical: 2,
  },
  table_scroll: {
    maxWidth: '100%',
    marginVertical: theme.spacing.sm,
  },
  table_scroll_content: {
    paddingBottom: theme.spacing.xs,
  },
  table: {
    minWidth: 560,
    alignSelf: 'flex-start',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderHighlight,
    borderRadius: theme.radius.sm,
    overflow: 'hidden',
    backgroundColor: theme.colors.bgElevated,
  },
  thead: {
    backgroundColor: theme.colors.bgItem,
  },
  tbody: {
    backgroundColor: theme.colors.bgElevated,
  },
  tr: {
    flexDirection: 'row',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderLight,
  },
  th: {
    flex: 0,
    width: 176,
    minWidth: 176,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.sm,
  },
  td: {
    flex: 0,
    width: 176,
    minWidth: 176,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.sm,
  },
  strong: {
    fontWeight: '700',
    color: theme.colors.textPrimary,
  },
  em: {
    fontStyle: 'italic',
  },
});